import { component$ } from "@builder.io/qwik";

export default component$(() => {
    return (
        <div class="container mx-auto mt-24 px-4 py-8">
            <h1 class="text-3xl font-bold text-emerald-700 mb-4">Privacy Policy</h1>
            <p class="text-gray-700 mb-6">Last updated: April 25, 2025</p>
            <p class="text-gray-600 mb-4">
                This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p class="text-gray-600 mb-6">
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>

            <h2 class="text-2xl font-semibold text-emerald-700 mb-4">Interpretation and Definitions</h2>
            <h3 class="text-xl font-semibold text-emerald-600 mb-2">Interpretation</h3>
            <p class="text-gray-600 mb-4">
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 class="text-xl font-semibold text-emerald-600 mb-2">Definitions</h3>
            <p class="text-gray-600 mb-4">For the purposes of this Privacy Policy:</p>
            <ul class="list-disc list-inside text-gray-600 mb-6">
                <li class="mb-2">
                    <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
                </li>
                <li class="mb-2">
                    <strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.
                </li>
                <li class="mb-2">
                    <strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Automate AIoT, No 28, Beach Road, Alles Garden, Trincomalee 31000.
                </li>
                <li class="mb-2">
                    <strong>Cookies</strong> are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.
                </li>
                <li class="mb-2">
                    <strong>Country</strong> refers to: Sri Lanka
                </li>
                <li class="mb-2">
                    <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.
                </li>
                <li class="mb-2">
                    <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
                </li>
                <li class="mb-2">
                    <strong>Service</strong> refers to the Website.
                </li>
                <li class="mb-2">
                    <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.
                </li>
                <li class="mb-2">
                    <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                </li>
                <li class="mb-2">
                    <strong>Website</strong> refers to AutomatewithAIoT, accessible from <a href="http://www.automatewithaiot.com" class="text-emerald-600 underline" rel="external nofollow noopener" target="_blank">http://www.automatewithaiot.com</a>
                </li>
                <li class="mb-2">
                    <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                </li>
            </ul>

            <h2 class="text-2xl font-semibold text-emerald-700 mb-4">Contact Us</h2>
            <p class="text-gray-600 mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul class="list-disc list-inside text-gray-600">
                <li class="mb-2">
                    By email: <a href="mailto:support@automatewithaiot.com" class="text-emerald-600 underline">support@automatewithaiot.com</a>
                </li>
                <li class="mb-2">
                    By visiting this page on our website: <a href="https://automatewithaiot.com/contact/" class="text-emerald-600 underline" rel="external nofollow noopener" target="_blank">https://automatewithaiot.com/contact/</a>
                </li>
            </ul>
        </div>
    );
});